Set up Husky pre-push hook

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,4 +1,6 @@
-#!/usr/bin/env sh
-. "$(dirname -- "$0")/_/husky.sh"
+#!/bin/sh
+. "$(dirname "$0")/_/husky.sh"
 
-dart format . --line-length 120 && dart fix --apply 
+# Run your custom pre-push checks (e.g., Dart analysis, formatting, etc.)
+dart format . --line-length 120 && dart fix --apply && flutter analyze --no-cache --verbose | tee result.log | grep -qv 'warning\|error' && echo 'No issues found' || { echo 'Flutter analyze found warnings or errors. Please fix them before pushing.'; exit 1; }
+
